//Payment
export const GET_PAYMENT_START="GET_PAYMENT_START"
export const GET_PAYMENT_SUCCESS="GET_PAYMENT_SUCCESS"
export const GET_PAYMENT_FAIL="GET_PAYMENT_FAIL"
export const PAYMENT_SUCCESS="PAYMENT_SUCCESS"

export const CASH_ON_DELIVERY_START="CASH_ON_DELIVERY_START"
export const CASH_ON_DELIVERY_SUCCESS="CASH_ON_DELIVERY_SUCCESS"
export const CASH_ON_DELIVERY_FAIL="CASH_ON_DELIVERY_FAIL"
//Product
export const Get_Product_start="get_product"
export const Get_Product_Success="get_product_success"
export const Get_Product_Fail="get_product_fail"
//User
export const AUTH_START="AUTH_START"
export const AUTH_SUCCESS='AUTH_SUCCESS'
export const AUTH_FAIL='AUTH_FAIL'
export const AUTH_LOGOUT='AUTH_LOGOUT'

export const GET_TRANSACTION_STATUS_START='GET_TRANSACTION_STATUS_START'
export const GET_TRANSACTION_STATUS_SUCCESS='GET_TRANSACTION_STATUS_SUCCESS'
export const GET_TRANSACTION_STATUS_FAIL='GET_TRANSACTION_STATUS_FAIL'
//Whatsapp
export const OTP_Start="OTP_Start"
export const OTP_Success="OTP_Success"
export const OTP_Fail="OTP_Fail"

//Address
export const CREATE_ADDRESS_START='CREATE_ADDRESS_START'
export const CREATE_ADDRESS_SUCCESS='CREATE_ADDRESS_SUCCESS'
export const CREATE_ADDRESS_FAIL='CREATE_ADDRESS_FAIL'

export const GET_ADDRESS_START='GET_ADDRESS_START'
export const GET_ADDRESS_SUCCESS='GET_ADDRESS_SUCCESS'
export const GET_ADDRESS_FAIL='GET_ADDRESS_FAIL'

export const DEL_ADDRESS_START='DEL_ADDRESS_START'
export const DEL_ADDRESS_SUCCESS='DEL_ADDRESS_SUCCESS'
export const DEL_ADDRESS_FAIL='DEL_ADDRESS_FAIL'

export const SET_ADDRESS_START='SET_ADDRESS_START'
export const SET_ADDRESS_SUCCESS='SET_ADDRESS_SUCCESS'
export const SET_ADDRESS_FAIL='SET_ADDRESS_FAIL'

//CART
export const ADD_ITEM_START="ADD_ITEM_START"
export const ADD_ITEM_SUCCESS="ADD_ITEM_SUCCESS"
export const ADD_ITEM_FAIL="ADD_ITEM_FAIL"

export const UPDATE_ITEM_START="UPDATE_ITEM_START"
export const UPDATE_ITEM_SUCCESS="UPDATE_ITEM_SUCCESS"
export const UPDATE_ITEM_FAIL="UPDATE_ITEM_FAIL"

export const DELETE_ITEM_START="DELETE_ITEM_START"
export const DELETE_ITEM_SUCCESS="DELETE_ITEM_SUCCESS"
export const DELETE_ITEM_FAIL="DELETE_ITEM_FAIL"

export const GET_ITEM_START="GET_ITEM_START"
export const GET_ITEM_SUCCESS="GET_ITEM_SUCCESS"
export const GET_ITEM_FAIL="GET_ITEM_FAIL"

export const EMPTY_CART="EMPTY_CART"
export const RESET="RESET"
export const TOGGLE_CART="TOGGLE_CART"
//CART